matrix:
  include:
    - language: go
      go:
        - 1.14.4
      before-install:
        - cd md-wiki-api
      script:
        - go test -v ./...

    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd md-wiki-client
